// <auto-generated />
namespace Chaty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EnhancedChatModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnhancedChatModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202505271941489_EnhancedChatModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
